# Form implementation generated from reading ui file '.\\templates\\dlgGestionProp.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgGestionProp(object):
    def setupUi(self, dlgGestionProp):
        dlgGestionProp.setObjectName("dlgGestionProp")
        dlgGestionProp.resize(397, 298)
        dlgGestionProp.setModal(True)
        self.frame = QtWidgets.QFrame(parent=dlgGestionProp)
        self.frame.setGeometry(QtCore.QRect(0, -4, 399, 221))
        self.frame.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(70, 120, 275, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(275, 2))
        self.label.setMaximumSize(QtCore.QSize(230, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.txtTipoProp = QtWidgets.QLineEdit(parent=self.frame)
        self.txtTipoProp.setGeometry(QtCore.QRect(110, 160, 181, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.txtTipoProp.sizePolicy().hasHeightForWidth())
        self.txtTipoProp.setSizePolicy(sizePolicy)
        self.txtTipoProp.setObjectName("txtTipoProp")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(140, 10, 141, 121))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(".\\\\templates\\../img/house.ico"))
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(parent=dlgGestionProp)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 240, 275, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnAltaTipoProp = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btnAltaTipoProp.setMaximumSize(QtCore.QSize(100, 25))
        self.btnAltaTipoProp.setObjectName("btnAltaTipoProp")
        self.horizontalLayout.addWidget(self.btnAltaTipoProp)
        self.btnDelTipoProp = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btnDelTipoProp.setMinimumSize(QtCore.QSize(100, 0))
        self.btnDelTipoProp.setMaximumSize(QtCore.QSize(100, 25))
        self.btnDelTipoProp.setObjectName("btnDelTipoProp")
        self.horizontalLayout.addWidget(self.btnDelTipoProp)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)

        self.retranslateUi(dlgGestionProp)
        QtCore.QMetaObject.connectSlotsByName(dlgGestionProp)

    def retranslateUi(self, dlgGestionProp):
        _translate = QtCore.QCoreApplication.translate
        dlgGestionProp.setWindowTitle(_translate("dlgGestionProp", "Dialog"))
        self.label.setText(_translate("dlgGestionProp", "Introduzca tipo de propiedad a crear o eliminar:"))
        self.btnAltaTipoProp.setText(_translate("dlgGestionProp", "Alta"))
        self.btnDelTipoProp.setText(_translate("dlgGestionProp", "Elimninar"))
