# Form implementation generated from reading ui file '.\\templates\\ventPrincipal.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ventPrincipal(object):
    def setupUi(self, ventPrincipal):
        ventPrincipal.setObjectName("ventPrincipal")
        ventPrincipal.resize(1216, 768)
        ventPrincipal.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\\\templates\\../img/logo.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        ventPrincipal.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=ventPrincipal)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 3, 1, 1)
        self.panPrincipal = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.panPrincipal.setStyleSheet("")
        self.panPrincipal.setObjectName("panPrincipal")
        self.PesClientes = QtWidgets.QWidget()
        self.PesClientes.setObjectName("PesClientes")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.PesClientes)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lblMuniCli = QtWidgets.QLabel(parent=self.PesClientes)
        self.lblMuniCli.setObjectName("lblMuniCli")
        self.gridLayout.addWidget(self.lblMuniCli, 3, 10, 1, 1)
        self.txtMovilCli = QtWidgets.QLineEdit(parent=self.PesClientes)
        self.txtMovilCli.setMinimumSize(QtCore.QSize(150, 0))
        self.txtMovilCli.setMaximumSize(QtCore.QSize(150, 16777215))
        self.txtMovilCli.setObjectName("txtMovilCli")
        self.gridLayout.addWidget(self.txtMovilCli, 2, 5, 1, 4)
        self.txtNomCli = QtWidgets.QLineEdit(parent=self.PesClientes)
        self.txtNomCli.setMinimumSize(QtCore.QSize(200, 0))
        self.txtNomCli.setMaximumSize(QtCore.QSize(200, 16777215))
        self.txtNomCli.setObjectName("txtNomCli")
        self.gridLayout.addWidget(self.txtNomCli, 1, 5, 1, 7)
        self.lblEmailCli = QtWidgets.QLabel(parent=self.PesClientes)
        self.lblEmailCli.setObjectName("lblEmailCli")
        self.gridLayout.addWidget(self.lblEmailCli, 2, 1, 1, 1)
        self.txtEmailCli = QtWidgets.QLineEdit(parent=self.PesClientes)
        self.txtEmailCli.setMinimumSize(QtCore.QSize(300, 0))
        self.txtEmailCli.setMaximumSize(QtCore.QSize(450, 16777215))
        self.txtEmailCli.setObjectName("txtEmailCli")
        self.gridLayout.addWidget(self.txtEmailCli, 2, 2, 1, 1)
        self.cmbProCli = QtWidgets.QComboBox(parent=self.PesClientes)
        self.cmbProCli.setMinimumSize(QtCore.QSize(120, 0))
        self.cmbProCli.setMaximumSize(QtCore.QSize(120, 16777215))
        self.cmbProCli.setObjectName("cmbProCli")
        self.gridLayout.addWidget(self.cmbProCli, 3, 8, 1, 1)
        self.cmbMuniCli = QtWidgets.QComboBox(parent=self.PesClientes)
        self.cmbMuniCli.setMinimumSize(QtCore.QSize(200, 0))
        self.cmbMuniCli.setObjectName("cmbMuniCli")
        self.gridLayout.addWidget(self.cmbMuniCli, 3, 11, 1, 2)
