# Form implementation generated from reading ui file 'ventPrincipal.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ventPrincipal(object):
    def setupUi(self, ventPrincipal):
        ventPrincipal.setObjectName("ventPrincipal")
        ventPrincipal.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=ventPrincipal)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(350, 250, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.ibTitulo = QtWidgets.QLabel(parent=self.centralwidget)
        self.ibTitulo.setGeometry(QtCore.QRect(260, 90, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ibTitulo.setFont(font)
        self.ibTitulo.setObjectName("ibTitulo")
        ventPrincipal.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=ventPrincipal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        ventPrincipal.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=ventPrincipal)
        self.statusbar.setObjectName("statusbar")
        ventPrincipal.setStatusBar(self.statusbar)

        self.retranslateUi(ventPrincipal)
        QtCore.QMetaObject.connectSlotsByName(ventPrincipal)

    def retranslateUi(self, ventPrincipal):
        _translate = QtCore.QCoreApplication.translate
        ventPrincipal.setWindowTitle(_translate("ventPrincipal", "InmoTeis"))
        self.pushButton.setText(_translate("ventPrincipal", "Aceptar"))
        self.ibTitulo.setText(_translate("ventPrincipal", "Empresa Inmobiliaria de Teis"))
